/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Alias {
  createdAt: Generated<Timestamp>;
  elementId: string;
  hits: Generated<number>;
  id: Generated<string>;
  memoryVersionId: string;
  phrase: string;
  source: string;
  stateFingerprint: string | null;
  tenantId: string;
  updatedAt: Generated<Timestamp>;
}

export interface Application {
  /**
   * How a background browser authenticates against this application. Holds secret references only — never a credential. Validated against protocol.AuthProfile on read.
   */
  authProfile: Generated<Json>;
  baseUrl: string;
  createdAt: Generated<Timestamp>;
  env: string;
  id: Generated<string>;
  name: string;
  /**
   * Whether /v1/seed/execute may write to this application. Production requires an explicit, audited opt-in; every other environment is allowed by default.
   */
  seedingAllowed: Generated<boolean | null>;
  seedingEnabledAt: Timestamp | null;
  seedingEnabledBy: string | null;
  seedingEnabledReason: string | null;
  tenantId: string;
  updatedAt: Generated<Timestamp>;
}

export interface AtlasSchemaRevisionsAtlasSchemaRevision {
  applied: Generated<Int8>;
  description: string;
  error: string | null;
  errorStmt: string | null;
  executedAt: Timestamp;
  executionTime: Int8;
  hash: string;
  operatorVersion: string;
  partialHashes: Json | null;
  total: Generated<Int8>;
  type: Generated<Int8>;
  version: string;
}

export interface AuditLog {
  action: string;
  actor: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  metadata: Generated<Json>;
  target: string;
  tenantId: string;
}

export interface DriftReport {
  aliasMigrationRate: Numeric | null;
  approvedBy: string | null;
  /**
   * The building memory version a reconcile produced, which approving this report activates. Null until reconciliation has built one. Approval flips its status rather than editing memory in place, so a session resolving against the current version keeps working.
   */
  candidateMemoryVersionId: string | null;
  createdAt: Generated<Timestamp>;
  detectedBy: string;
  diff: Json | null;
  expectedStructuralHash: string;
  id: Generated<string>;
  memoryVersionId: string;
  /**
   * The concrete path the drift was seen at, e.g. /orders/4903. Kept because route_pattern cannot be navigated to and a reconcile job lost to a Redis restart must be re-enqueueable.
   */
  observedRoute: string;
  observedStructuralHash: string;
  resolvedAt: Timestamp | null;
  routePattern: string;
  screenId: string;
  stateFingerprint: string;
  status: Generated<string>;
  tenantId: string;
  updatedAt: Generated<Timestamp>;
}

export interface Element {
  accessibleNameHash: string;
  confidence: Numeric;
  createdAt: Generated<Timestamp>;
  elementKey: string;
  fingerprint: Json;
  id: Generated<string>;
  role: string;
  screenId: string;
  stability: Numeric;
  tenantId: string;
}

export interface EntitySchema {
  confidence: Numeric;
  createdAt: Generated<Timestamp>;
  /**
   * Element key of the indexed control that removes one record of this entity, or null when none was found. Null becomes InverseOperation {kind:"none"} and is shown in the seed preview before anything is created.
   */
  deleteFlowElementKey: string | null;
  entityName: string;
  id: Generated<string>;
  memoryVersionId: string;
  observedCount: Generated<number>;
  tenantId: string;
  updatedAt: Generated<Timestamp>;
}

export interface FieldSpec {
  controlElementKey: string | null;
  createdAt: Generated<Timestamp>;
  derivedRule: Json | null;
  distribution: Json | null;
  entitySchemaId: string;
  enumValues: Json | null;
  id: Generated<string>;
  isUnique: Generated<boolean>;
  name: string;
  referencesEntity: string | null;
  required: boolean;
  tenantId: string;
  type: string;
  updatedAt: Generated<Timestamp>;
  valueConstraints: Generated<Json>;
}

export interface Materializer {
  createdAt: Generated<Timestamp>;
  entitySchemaId: string;
  id: Generated<string>;
  kind: string;
  priority: number;
  spec: Json;
  tenantId: string;
  updatedAt: Generated<Timestamp>;
  verificationTtlHours: Generated<number>;
  verifiedAt: Timestamp | null;
}

export interface MemoryVersion {
  applicationId: string;
  approvedBy: string | null;
  createdAt: Generated<Timestamp>;
  failureReason: string | null;
  id: Generated<string>;
  status: string;
  tenantId: string;
  updatedAt: Generated<Timestamp>;
  version: number;
}

export interface NavEdge {
  confidence: Numeric;
  createdAt: Generated<Timestamp>;
  fromScreen: string;
  id: Generated<string>;
  memoryVersionId: string;
  preconditions: Generated<Json>;
  tenantId: string;
  toScreen: string;
  triggerElement: string;
}

export interface Screen {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  indexedAt: Generated<Timestamp>;
  label: string;
  memoryVersionId: string;
  routePattern: string;
  stateFingerprint: string;
  structuralHash: string;
  tenantId: string;
}

export interface SeedLedger {
  adapterUsed: string;
  createdAt: Generated<Timestamp>;
  entity: string;
  entitySchemaId: string | null;
  externalRef: string;
  id: Generated<string>;
  inverseOp: Json;
  nodeId: string;
  payload: Json;
  planId: string;
  provenance: Json;
  revertedAt: Timestamp | null;
  sessionId: string;
  tenantId: string;
  updatedAt: Generated<Timestamp>;
}

export interface Session {
  applicationId: string;
  createdAt: Generated<Timestamp>;
  endedAt: Timestamp | null;
  id: Generated<string>;
  memoryVersionId: string;
  startedAt: Generated<Timestamp>;
  tenantId: string;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface SessionStep {
  actionClass: string | null;
  confidence: Numeric | null;
  createdAt: Generated<Timestamp>;
  elementId: string | null;
  evidence: Generated<Json>;
  id: Generated<string>;
  intent: Json;
  latencyMs: Numeric;
  ordinal: number;
  outcome: string;
  resolution: Json;
  sessionId: string;
  tenantId: string;
  tier: string | null;
  utterance: string;
}

export interface Tenant {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface User {
  createdAt: Generated<Timestamp>;
  email: string;
  id: Generated<string>;
  role: string;
  tenantId: string;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  aliases: Alias;
  applications: Application;
  "atlasSchemaRevisions.atlasSchemaRevisions": AtlasSchemaRevisionsAtlasSchemaRevision;
  auditLog: AuditLog;
  driftReports: DriftReport;
  elements: Element;
  entitySchemas: EntitySchema;
  fieldSpecs: FieldSpec;
  materializers: Materializer;
  memoryVersions: MemoryVersion;
  navEdges: NavEdge;
  screens: Screen;
  seedLedger: SeedLedger;
  sessions: Session;
  sessionSteps: SessionStep;
  tenants: Tenant;
  users: User;
}
